// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bluechipchain/liquidityvault/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_Deposit_FullMethodName            = "/bluechipchain.liquidityvault.Msg/Deposit"
	Msg_InitiateWithdrawal_FullMethodName = "/bluechipchain.liquidityvault.Msg/InitiateWithdrawal"
	Msg_SetRewardShare_FullMethodName     = "/bluechipchain.liquidityvault.Msg/SetRewardShare"
	Msg_AllocateToPool_FullMethodName     = "/bluechipchain.liquidityvault.Msg/AllocateToPool"
	Msg_DeallocateFromPool_FullMethodName = "/bluechipchain.liquidityvault.Msg/DeallocateFromPool"
	Msg_CollectPoolRewards_FullMethodName = "/bluechipchain.liquidityvault.Msg/CollectPoolRewards"
	Msg_ClaimVaultRewards_FullMethodName  = "/bluechipchain.liquidityvault.Msg/ClaimVaultRewards"
	Msg_RegisterPool_FullMethodName       = "/bluechipchain.liquidityvault.Msg/RegisterPool"
	Msg_SetPoolEnabled_FullMethodName     = "/bluechipchain.liquidityvault.Msg/SetPoolEnabled"
	Msg_UpdateParams_FullMethodName       = "/bluechipchain.liquidityvault.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// Deposit moves bond-denom tokens from the validator's own account into
	// its Liquidity Vault. The deposit counts toward the validator's composite
	// score.
	Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgDepositResponse, error)
	// InitiateWithdrawal starts a withdrawal from the validator's vault. The
	// amount immediately stops counting toward the composite score and is
	// released to the validator's account after the universal grace period.
	InitiateWithdrawal(ctx context.Context, in *MsgInitiateWithdrawal, opts ...grpc.CallOption) (*MsgInitiateWithdrawalResponse, error)
	// SetRewardShare sets the fraction of vault liquidity rewards passed
	// through to delegators. This is the only vault parameter a validator can
	// change in stage 1 of the LPV rollout.
	SetRewardShare(ctx context.Context, in *MsgSetRewardShare, opts ...grpc.CallOption) (*MsgSetRewardShareResponse, error)
	// AllocateToPool moves active vault balance into a registered liquidity
	// pool. The resulting pool position counts toward the composite score at
	// its current value.
	AllocateToPool(ctx context.Context, in *MsgAllocateToPool, opts ...grpc.CallOption) (*MsgAllocateToPoolResponse, error)
	// DeallocateFromPool requests removal of liquidity from a pool. The
	// liquidity keeps earning (and counting toward the composite score) until
	// the universal deallocation grace period ends; the withdrawn funds then
	// go to the validator's own account, leaving the vault.
	DeallocateFromPool(ctx context.Context, in *MsgDeallocateFromPool, opts ...grpc.CallOption) (*MsgDeallocateFromPoolResponse, error)
	// CollectPoolRewards pulls the accrued liquidity fees for the module's
	// position in a pool and distributes them: each participating validator's
	// cut (pro rata by internal shares) is split by that vault's delegator
	// reward share — the validator's part is paid out immediately, the
	// delegators' part accrues to their claimable rewards.
	CollectPoolRewards(ctx context.Context, in *MsgCollectPoolRewards, opts ...grpc.CallOption) (*MsgCollectPoolRewardsResponse, error)
	// ClaimVaultRewards pays out a delegator's accrued vault rewards for one
	// validator.
	ClaimVaultRewards(ctx context.Context, in *MsgClaimVaultRewards, opts ...grpc.CallOption) (*MsgClaimVaultRewardsResponse, error)
	// RegisterPool registers a liquidity pool contract that vaults may supply
	// liquidity to. Governance gated.
	RegisterPool(ctx context.Context, in *MsgRegisterPool, opts ...grpc.CallOption) (*MsgRegisterPoolResponse, error)
	// SetPoolEnabled enables or disables new allocations to a registered
	// pool. Governance gated. Deallocations are always allowed.
	SetPoolEnabled(ctx context.Context, in *MsgSetPoolEnabled, opts ...grpc.CallOption) (*MsgSetPoolEnabledResponse, error)
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDepositResponse)
	err := c.cc.Invoke(ctx, Msg_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitiateWithdrawal(ctx context.Context, in *MsgInitiateWithdrawal, opts ...grpc.CallOption) (*MsgInitiateWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgInitiateWithdrawalResponse)
	err := c.cc.Invoke(ctx, Msg_InitiateWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetRewardShare(ctx context.Context, in *MsgSetRewardShare, opts ...grpc.CallOption) (*MsgSetRewardShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSetRewardShareResponse)
	err := c.cc.Invoke(ctx, Msg_SetRewardShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AllocateToPool(ctx context.Context, in *MsgAllocateToPool, opts ...grpc.CallOption) (*MsgAllocateToPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAllocateToPoolResponse)
	err := c.cc.Invoke(ctx, Msg_AllocateToPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeallocateFromPool(ctx context.Context, in *MsgDeallocateFromPool, opts ...grpc.CallOption) (*MsgDeallocateFromPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDeallocateFromPoolResponse)
	err := c.cc.Invoke(ctx, Msg_DeallocateFromPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CollectPoolRewards(ctx context.Context, in *MsgCollectPoolRewards, opts ...grpc.CallOption) (*MsgCollectPoolRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCollectPoolRewardsResponse)
	err := c.cc.Invoke(ctx, Msg_CollectPoolRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimVaultRewards(ctx context.Context, in *MsgClaimVaultRewards, opts ...grpc.CallOption) (*MsgClaimVaultRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgClaimVaultRewardsResponse)
	err := c.cc.Invoke(ctx, Msg_ClaimVaultRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterPool(ctx context.Context, in *MsgRegisterPool, opts ...grpc.CallOption) (*MsgRegisterPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterPoolResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetPoolEnabled(ctx context.Context, in *MsgSetPoolEnabled, opts ...grpc.CallOption) (*MsgSetPoolEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSetPoolEnabledResponse)
	err := c.cc.Invoke(ctx, Msg_SetPoolEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// Deposit moves bond-denom tokens from the validator's own account into
	// its Liquidity Vault. The deposit counts toward the validator's composite
	// score.
	Deposit(context.Context, *MsgDeposit) (*MsgDepositResponse, error)
	// InitiateWithdrawal starts a withdrawal from the validator's vault. The
	// amount immediately stops counting toward the composite score and is
	// released to the validator's account after the universal grace period.
	InitiateWithdrawal(context.Context, *MsgInitiateWithdrawal) (*MsgInitiateWithdrawalResponse, error)
	// SetRewardShare sets the fraction of vault liquidity rewards passed
	// through to delegators. This is the only vault parameter a validator can
	// change in stage 1 of the LPV rollout.
	SetRewardShare(context.Context, *MsgSetRewardShare) (*MsgSetRewardShareResponse, error)
	// AllocateToPool moves active vault balance into a registered liquidity
	// pool. The resulting pool position counts toward the composite score at
	// its current value.
	AllocateToPool(context.Context, *MsgAllocateToPool) (*MsgAllocateToPoolResponse, error)
	// DeallocateFromPool requests removal of liquidity from a pool. The
	// liquidity keeps earning (and counting toward the composite score) until
	// the universal deallocation grace period ends; the withdrawn funds then
	// go to the validator's own account, leaving the vault.
	DeallocateFromPool(context.Context, *MsgDeallocateFromPool) (*MsgDeallocateFromPoolResponse, error)
	// CollectPoolRewards pulls the accrued liquidity fees for the module's
	// position in a pool and distributes them: each participating validator's
	// cut (pro rata by internal shares) is split by that vault's delegator
	// reward share — the validator's part is paid out immediately, the
	// delegators' part accrues to their claimable rewards.
	CollectPoolRewards(context.Context, *MsgCollectPoolRewards) (*MsgCollectPoolRewardsResponse, error)
	// ClaimVaultRewards pays out a delegator's accrued vault rewards for one
	// validator.
	ClaimVaultRewards(context.Context, *MsgClaimVaultRewards) (*MsgClaimVaultRewardsResponse, error)
	// RegisterPool registers a liquidity pool contract that vaults may supply
	// liquidity to. Governance gated.
	RegisterPool(context.Context, *MsgRegisterPool) (*MsgRegisterPoolResponse, error)
	// SetPoolEnabled enables or disables new allocations to a registered
	// pool. Governance gated. Deallocations are always allowed.
	SetPoolEnabled(context.Context, *MsgSetPoolEnabled) (*MsgSetPoolEnabledResponse, error)
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) Deposit(context.Context, *MsgDeposit) (*MsgDepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedMsgServer) InitiateWithdrawal(context.Context, *MsgInitiateWithdrawal) (*MsgInitiateWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateWithdrawal not implemented")
}
func (UnimplementedMsgServer) SetRewardShare(context.Context, *MsgSetRewardShare) (*MsgSetRewardShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRewardShare not implemented")
}
func (UnimplementedMsgServer) AllocateToPool(context.Context, *MsgAllocateToPool) (*MsgAllocateToPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateToPool not implemented")
}
func (UnimplementedMsgServer) DeallocateFromPool(context.Context, *MsgDeallocateFromPool) (*MsgDeallocateFromPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeallocateFromPool not implemented")
}
func (UnimplementedMsgServer) CollectPoolRewards(context.Context, *MsgCollectPoolRewards) (*MsgCollectPoolRewardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectPoolRewards not implemented")
}
func (UnimplementedMsgServer) ClaimVaultRewards(context.Context, *MsgClaimVaultRewards) (*MsgClaimVaultRewardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimVaultRewards not implemented")
}
func (UnimplementedMsgServer) RegisterPool(context.Context, *MsgRegisterPool) (*MsgRegisterPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPool not implemented")
}
func (UnimplementedMsgServer) SetPoolEnabled(context.Context, *MsgSetPoolEnabled) (*MsgSetPoolEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPoolEnabled not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Deposit(ctx, req.(*MsgDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitiateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiateWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitiateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_InitiateWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitiateWithdrawal(ctx, req.(*MsgInitiateWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetRewardShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetRewardShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetRewardShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetRewardShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetRewardShare(ctx, req.(*MsgSetRewardShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AllocateToPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAllocateToPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AllocateToPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AllocateToPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AllocateToPool(ctx, req.(*MsgAllocateToPool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeallocateFromPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeallocateFromPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeallocateFromPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeallocateFromPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeallocateFromPool(ctx, req.(*MsgDeallocateFromPool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CollectPoolRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCollectPoolRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CollectPoolRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CollectPoolRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CollectPoolRewards(ctx, req.(*MsgCollectPoolRewards))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimVaultRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimVaultRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimVaultRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClaimVaultRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimVaultRewards(ctx, req.(*MsgClaimVaultRewards))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterPool(ctx, req.(*MsgRegisterPool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetPoolEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetPoolEnabled)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetPoolEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetPoolEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetPoolEnabled(ctx, req.(*MsgSetPoolEnabled))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bluechipchain.liquidityvault.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deposit",
			Handler:    _Msg_Deposit_Handler,
		},
		{
			MethodName: "InitiateWithdrawal",
			Handler:    _Msg_InitiateWithdrawal_Handler,
		},
		{
			MethodName: "SetRewardShare",
			Handler:    _Msg_SetRewardShare_Handler,
		},
		{
			MethodName: "AllocateToPool",
			Handler:    _Msg_AllocateToPool_Handler,
		},
		{
			MethodName: "DeallocateFromPool",
			Handler:    _Msg_DeallocateFromPool_Handler,
		},
		{
			MethodName: "CollectPoolRewards",
			Handler:    _Msg_CollectPoolRewards_Handler,
		},
		{
			MethodName: "ClaimVaultRewards",
			Handler:    _Msg_ClaimVaultRewards_Handler,
		},
		{
			MethodName: "RegisterPool",
			Handler:    _Msg_RegisterPool_Handler,
		},
		{
			MethodName: "SetPoolEnabled",
			Handler:    _Msg_SetPoolEnabled_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bluechipchain/liquidityvault/tx.proto",
}
