// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bluechipchain/liquidityvault/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the liquidityvault module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// vaults are the Liquidity Vaults of all validators.
	Vaults []Vault `protobuf:"bytes,2,rep,name=vaults,proto3" json:"vaults"`
	// pending_withdrawals are vault withdrawals still waiting out the grace
	// period.
	PendingWithdrawals []PendingWithdrawal `protobuf:"bytes,3,rep,name=pending_withdrawals,json=pendingWithdrawals,proto3" json:"pending_withdrawals"`
	// pools are the governance-registered liquidity pools.
	Pools []RegisteredPool `protobuf:"bytes,4,rep,name=pools,proto3" json:"pools"`
	// next_pool_id is the id assigned to the next registered pool.
	NextPoolId uint64 `protobuf:"varint,5,opt,name=next_pool_id,json=nextPoolId,proto3" json:"next_pool_id,omitempty"`
	// positions are the validators' internal shares of pool positions.
	Positions []PoolPosition `protobuf:"bytes,6,rep,name=positions,proto3" json:"positions"`
	// pending_deallocations are pool exits still waiting out the deallocation
	// grace period.
	PendingDeallocations []PendingDeallocation `protobuf:"bytes,7,rep,name=pending_deallocations,json=pendingDeallocations,proto3" json:"pending_deallocations"`
	// value_post_histories are the validators' rolling value-post windows.
	ValuePostHistories []ValuePostHistory `protobuf:"bytes,8,rep,name=value_post_histories,json=valuePostHistories,proto3" json:"value_post_histories"`
	// scheduled_value_posts is the pending value-post schedule.
	ScheduledValuePosts []ScheduledValuePost `protobuf:"bytes,9,rep,name=scheduled_value_posts,json=scheduledValuePosts,proto3" json:"scheduled_value_posts"`
	// cached_pool_values are the last observed position values per pool (the
	// dark-pool valuation fallback).
	CachedPoolValues []CachedPoolValue `protobuf:"bytes,10,rep,name=cached_pool_values,json=cachedPoolValues,proto3" json:"cached_pool_values"`
	// delegator_rewards are the delegators' vault-reward accrual records.
	DelegatorRewards []DelegatorReward `protobuf:"bytes,11,rep,name=delegator_rewards,json=delegatorRewards,proto3" json:"delegator_rewards"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6781941e95ad1ac1, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetVaults() []Vault {
	if m != nil {
		return m.Vaults
	}
	return nil
}

func (m *GenesisState) GetPendingWithdrawals() []PendingWithdrawal {
	if m != nil {
		return m.PendingWithdrawals
	}
	return nil
}

func (m *GenesisState) GetPools() []RegisteredPool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetNextPoolId() uint64 {
	if m != nil {
		return m.NextPoolId
	}
	return 0
}

func (m *GenesisState) GetPositions() []PoolPosition {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetPendingDeallocations() []PendingDeallocation {
	if m != nil {
		return m.PendingDeallocations
	}
	return nil
}

func (m *GenesisState) GetValuePostHistories() []ValuePostHistory {
	if m != nil {
		return m.ValuePostHistories
	}
	return nil
}

func (m *GenesisState) GetScheduledValuePosts() []ScheduledValuePost {
	if m != nil {
		return m.ScheduledValuePosts
	}
	return nil
}

func (m *GenesisState) GetCachedPoolValues() []CachedPoolValue {
	if m != nil {
		return m.CachedPoolValues
	}
	return nil
}

func (m *GenesisState) GetDelegatorRewards() []DelegatorReward {
	if m != nil {
		return m.DelegatorRewards
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "bluechipchain.liquidityvault.GenesisState")
}

func init() {
	proto.RegisterFile("bluechipchain/liquidityvault/genesis.proto", fileDescriptor_6781941e95ad1ac1)
}

var fileDescriptor_6781941e95ad1ac1 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x1b, 0xd6, 0x75, 0xd4, 0xdd, 0x81, 0x79, 0x9d, 0x64, 0x55, 0x28, 0x54, 0x30, 0x89,
	0x52, 0x8d, 0x16, 0xc6, 0x1d, 0x89, 0x6e, 0xd2, 0xc6, 0x05, 0x55, 0x9d, 0x04, 0x12, 0x97, 0xe0,
	0xc5, 0x26, 0x35, 0xf2, 0xe2, 0x90, 0xcf, 0x69, 0xd7, 0xb7, 0xe0, 0x31, 0x38, 0xf2, 0x12, 0x48,
	0x3b, 0xee, 0xc8, 0x09, 0xa1, 0xf6, 0xc0, 0x6b, 0x20, 0x3b, 0xce, 0x46, 0x37, 0x29, 0xdd, 0x25,
	0x72, 0x3f, 0xff, 0xff, 0xff, 0x9f, 0xfb, 0x7d, 0x96, 0x51, 0xf7, 0x54, 0x66, 0x3c, 0x1c, 0x8b,
	0x24, 0x1c, 0x53, 0x11, 0xf7, 0xa5, 0xf8, 0x9a, 0x09, 0x26, 0xf4, 0x6c, 0x42, 0x33, 0xa9, 0xfb,
	0x11, 0x8f, 0x39, 0x08, 0xe8, 0x25, 0xa9, 0xd2, 0x0a, 0x3f, 0x5c, 0xd2, 0xf6, 0x96, 0xb5, 0xad,
	0x2d, 0x7a, 0x26, 0x62, 0xd5, 0xb7, 0xdf, 0xdc, 0xd0, 0x6a, 0x46, 0x2a, 0x52, 0x76, 0xd9, 0x37,
	0x2b, 0x57, 0x7d, 0x56, 0x8a, 0x4c, 0x68, 0x4a, 0xcf, 0x1c, 0xb1, 0xf5, 0xb4, 0x5c, 0xaa, 0x94,
	0x74, 0xc2, 0xbd, 0x52, 0xe1, 0x84, 0xca, 0x8c, 0x27, 0x0a, 0xb4, 0x53, 0x77, 0x56, 0xa8, 0x33,
	0xe9, 0x94, 0x8f, 0x7f, 0x6e, 0xa0, 0xcd, 0xa3, 0xbc, 0x09, 0x27, 0x9a, 0x6a, 0x8e, 0x8f, 0x50,
	0x2d, 0x3f, 0x21, 0xf1, 0xda, 0x5e, 0xa7, 0xb1, 0xbf, 0xdb, 0x2b, 0x6b, 0x4a, 0x6f, 0x68, 0xb5,
	0x83, 0xfa, 0xc5, 0xef, 0x47, 0x95, 0xef, 0x7f, 0x7f, 0x74, 0xbd, 0x91, 0xb3, 0xe3, 0x37, 0xa8,
	0x66, 0x25, 0x40, 0xee, 0xb5, 0xd7, 0x3a, 0x8d, 0xfd, 0x27, 0xe5, 0x41, 0xef, 0xcd, 0x77, 0x50,
	0x35, 0x39, 0x23, 0x67, 0xc4, 0x9f, 0xd1, 0x76, 0xc2, 0x63, 0x26, 0xe2, 0x28, 0x98, 0x0a, 0x3d,
	0x66, 0x29, 0x9d, 0x52, 0x09, 0x64, 0xcd, 0xe6, 0xf5, 0x57, 0x1c, 0x2c, 0x37, 0x7e, 0xb8, 0xf2,
	0xb9, 0x6c, 0x9c, 0xdc, 0xdc, 0x00, 0x7c, 0x8c, 0xd6, 0x4d, 0xab, 0x81, 0x54, 0x6d, 0xf2, 0x5e,
	0x79, 0xf2, 0x88, 0x47, 0x02, 0x34, 0x4f, 0x39, 0x1b, 0x2a, 0x55, 0xc4, 0xe6, 0x01, 0xb8, 0x8d,
	0x36, 0x63, 0x7e, 0xae, 0x03, 0xf3, 0x2b, 0x10, 0x8c, 0xac, 0xb7, 0xbd, 0x4e, 0x75, 0x84, 0x4c,
	0xcd, 0x88, 0xdf, 0x32, 0xfc, 0x0e, 0xd5, 0x13, 0x05, 0x42, 0x0b, 0x15, 0x03, 0xa9, 0x59, 0x5e,
	0x77, 0xc5, 0x3f, 0x51, 0x4a, 0x0e, 0x9d, 0xc5, 0xd1, 0xae, 0x23, 0xb0, 0x44, 0x3b, 0x45, 0x8f,
	0x18, 0xa7, 0x52, 0xaa, 0x90, 0xe6, 0xd9, 0x1b, 0x36, 0xfb, 0xe5, 0x9d, 0xba, 0x74, 0xf8, 0x9f,
	0xd3, 0x21, 0x9a, 0xc9, 0xed, 0x2d, 0x33, 0x91, 0xa6, 0xbd, 0x6b, 0x81, 0xb9, 0x6c, 0xc1, 0x58,
	0x80, 0x56, 0xa9, 0xe0, 0x40, 0xee, 0x5b, 0x58, 0x6f, 0xd5, 0x88, 0x65, 0xc6, 0x87, 0x0a, 0xf4,
	0xb1, 0xf5, 0xcd, 0x8a, 0x89, 0x4c, 0x96, 0xeb, 0x82, 0x03, 0xfe, 0x82, 0x76, 0x20, 0x1c, 0x73,
	0x96, 0x49, 0xce, 0x82, 0x6b, 0x22, 0x90, 0xba, 0x05, 0xbd, 0x28, 0x07, 0x9d, 0x14, 0xd6, 0x2b,
	0xa2, 0x43, 0x6d, 0xc3, 0xad, 0x1d, 0xc0, 0x14, 0xe1, 0x90, 0x9a, 0x7a, 0x3e, 0x35, 0x4b, 0x03,
	0x82, 0x2c, 0xe8, 0x79, 0x39, 0xe8, 0xc0, 0xfa, 0xcc, 0x80, 0x6c, 0x9e, 0xa3, 0x3c, 0x08, 0x97,
	0xcb, 0x80, 0x3f, 0xa1, 0x2d, 0xc6, 0x25, 0x8f, 0xa8, 0x56, 0x69, 0x90, 0xf2, 0x29, 0x4d, 0x19,
	0x90, 0xc6, 0x5d, 0x08, 0x87, 0x85, 0x6d, 0x64, 0x5d, 0x05, 0x81, 0x2d, 0x97, 0x61, 0xf0, 0xfa,
	0x62, 0xee, 0x7b, 0x97, 0x73, 0xdf, 0xfb, 0x33, 0xf7, 0xbd, 0x6f, 0x0b, 0xbf, 0x72, 0xb9, 0xf0,
	0x2b, 0xbf, 0x16, 0x7e, 0xe5, 0xe3, 0x6e, 0x91, 0x7f, 0x60, 0xdf, 0x82, 0xf3, 0x9b, 0xaf, 0x81,
	0x9e, 0x25, 0x1c, 0x4e, 0x6b, 0xf6, 0x39, 0x78, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x99,
	0x53, 0x86, 0x2f, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegatorRewards) > 0 {
		for iNdEx := len(m.DelegatorRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegatorRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.CachedPoolValues) > 0 {
		for iNdEx := len(m.CachedPoolValues) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CachedPoolValues[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ScheduledValuePosts) > 0 {
		for iNdEx := len(m.ScheduledValuePosts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ScheduledValuePosts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.ValuePostHistories) > 0 {
		for iNdEx := len(m.ValuePostHistories) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValuePostHistories[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.PendingDeallocations) > 0 {
		for iNdEx := len(m.PendingDeallocations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingDeallocations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.NextPoolId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPoolId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PendingWithdrawals) > 0 {
		for iNdEx := len(m.PendingWithdrawals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingWithdrawals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Vaults) > 0 {
		for iNdEx := len(m.Vaults) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vaults[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Vaults) > 0 {
		for _, e := range m.Vaults {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingWithdrawals) > 0 {
		for _, e := range m.PendingWithdrawals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextPoolId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPoolId))
	}
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingDeallocations) > 0 {
		for _, e := range m.PendingDeallocations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValuePostHistories) > 0 {
		for _, e := range m.ValuePostHistories {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ScheduledValuePosts) > 0 {
		for _, e := range m.ScheduledValuePosts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CachedPoolValues) > 0 {
		for _, e := range m.CachedPoolValues {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DelegatorRewards) > 0 {
		for _, e := range m.DelegatorRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vaults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vaults = append(m.Vaults, Vault{})
			if err := m.Vaults[len(m.Vaults)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingWithdrawals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingWithdrawals = append(m.PendingWithdrawals, PendingWithdrawal{})
			if err := m.PendingWithdrawals[len(m.PendingWithdrawals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, RegisteredPool{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPoolId", wireType)
			}
			m.NextPoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, PoolPosition{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingDeallocations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingDeallocations = append(m.PendingDeallocations, PendingDeallocation{})
			if err := m.PendingDeallocations[len(m.PendingDeallocations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValuePostHistories", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValuePostHistories = append(m.ValuePostHistories, ValuePostHistory{})
			if err := m.ValuePostHistories[len(m.ValuePostHistories)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledValuePosts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScheduledValuePosts = append(m.ScheduledValuePosts, ScheduledValuePost{})
			if err := m.ScheduledValuePosts[len(m.ScheduledValuePosts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CachedPoolValues", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CachedPoolValues = append(m.CachedPoolValues, CachedPoolValue{})
			if err := m.CachedPoolValues[len(m.CachedPoolValues)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorRewards = append(m.DelegatorRewards, DelegatorReward{})
			if err := m.DelegatorRewards[len(m.DelegatorRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
