// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bluechipchain/liquidityvault/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the liquidityvault module.
type Params struct {
	// stake_cap is the maximum number of bond-denom tokens a validator may have
	// bonded directly to the chain. Delegations that would push a validator's
	// tokens above this cap are rejected; capital above the cap is expected to
	// flow into the validator's Liquidity Vault instead. A value of zero
	// disables the cap.
	StakeCap cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=stake_cap,json=stakeCap,proto3,customtype=cosmossdk.io/math.Int" json:"stake_cap"`
	// withdrawal_grace_period is the universal delay between a vault withdrawal
	// request and the release of the funds. It protects pools against sudden
	// liquidity swings and is set protocol-wide, not per validator.
	WithdrawalGracePeriod time.Duration `protobuf:"bytes,2,opt,name=withdrawal_grace_period,json=withdrawalGracePeriod,proto3,stdduration" json:"withdrawal_grace_period"`
	// deallocation_grace_period is the universal delay ("Liquidity Providing
	// Change" in the LPV design document) between a validator requesting to
	// remove liquidity from a pool and the liquidity actually being removed.
	// Set protocol-wide, not per validator.
	DeallocationGracePeriod time.Duration `protobuf:"bytes,3,opt,name=deallocation_grace_period,json=deallocationGracePeriod,proto3,stdduration" json:"deallocation_grace_period"`
	// value_post_interval is the average time between a vault's value posts.
	// Actual post times are jittered pseudo-randomly within
	// [interval/2, interval*3/2) to mitigate gaming of the snapshots. The
	// design document's cadence is six posts per five-day complex-check
	// window (20h).
	ValuePostInterval time.Duration `protobuf:"bytes,4,opt,name=value_post_interval,json=valuePostInterval,proto3,stdduration" json:"value_post_interval"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a52f6c9b27b44fb, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWithdrawalGracePeriod() time.Duration {
	if m != nil {
		return m.WithdrawalGracePeriod
	}
	return 0
}

func (m *Params) GetDeallocationGracePeriod() time.Duration {
	if m != nil {
		return m.DeallocationGracePeriod
	}
	return 0
}

func (m *Params) GetValuePostInterval() time.Duration {
	if m != nil {
		return m.ValuePostInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "bluechipchain.liquidityvault.Params")
}

func init() {
	proto.RegisterFile("bluechipchain/liquidityvault/params.proto", fileDescriptor_2a52f6c9b27b44fb)
}

var fileDescriptor_2a52f6c9b27b44fb = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x3f, 0x0f, 0xd2, 0x40,
	0x18, 0xc6, 0x7b, 0x62, 0x88, 0xd4, 0x38, 0x50, 0x25, 0xfc, 0x89, 0x69, 0x89, 0xd1, 0x04, 0x31,
	0x5e, 0x13, 0xdd, 0x1c, 0x1c, 0xc0, 0x44, 0xd9, 0x08, 0x93, 0x71, 0xa9, 0x2f, 0xed, 0xd9, 0x5e,
	0xb8, 0xf6, 0xce, 0xde, 0x15, 0xe4, 0x2b, 0x38, 0x39, 0x3a, 0x3a, 0x38, 0x38, 0x32, 0xf8, 0x21,
	0x18, 0x89, 0x93, 0x71, 0x40, 0x03, 0x03, 0x7e, 0x0c, 0xc3, 0xb5, 0x44, 0x6a, 0x5c, 0x58, 0x9a,
	0xbe, 0x7f, 0x9e, 0xdf, 0xf3, 0x24, 0xf7, 0x9a, 0xf7, 0xa7, 0x2c, 0x23, 0x7e, 0x44, 0x85, 0x1f,
	0x01, 0x4d, 0x5c, 0x46, 0xdf, 0x66, 0x34, 0xa0, 0x6a, 0x39, 0x87, 0x8c, 0x29, 0x57, 0x40, 0x0a,
	0xb1, 0xc4, 0x22, 0xe5, 0x8a, 0x5b, 0xb7, 0x4b, 0xab, 0xb8, 0xbc, 0xda, 0xa9, 0x43, 0x4c, 0x13,
	0xee, 0xea, 0x6f, 0x2e, 0xe8, 0xb4, 0x7d, 0x2e, 0x63, 0x2e, 0x3d, 0x5d, 0xb9, 0x79, 0x51, 0x8c,
	0x6e, 0x85, 0x3c, 0xe4, 0x79, 0xff, 0xf8, 0x57, 0x74, 0xed, 0x90, 0xf3, 0x90, 0x11, 0x57, 0x57,
	0xd3, 0xec, 0x8d, 0x1b, 0x64, 0x29, 0x28, 0xca, 0x93, 0x7c, 0x7e, 0xe7, 0x73, 0xc5, 0xac, 0x8e,
	0x75, 0x24, 0xeb, 0x85, 0x59, 0x93, 0x0a, 0x66, 0xc4, 0xf3, 0x41, 0xb4, 0x50, 0x17, 0xf5, 0x6a,
	0x83, 0x07, 0xeb, 0xad, 0x63, 0xfc, 0xd8, 0x3a, 0x8d, 0xdc, 0x49, 0x06, 0x33, 0x4c, 0xb9, 0x1b,
	0x83, 0x8a, 0xf0, 0x28, 0x51, 0xdf, 0xbe, 0x3e, 0x34, 0x8b, 0x08, 0xa3, 0x44, 0x4d, 0xae, 0x69,
	0xf5, 0x10, 0x84, 0xf5, 0xda, 0x6c, 0x2e, 0xa8, 0x8a, 0x82, 0x14, 0x16, 0xc0, 0xbc, 0x30, 0x05,
	0x9f, 0x78, 0x82, 0xa4, 0x94, 0x07, 0xad, 0x2b, 0x5d, 0xd4, 0xbb, 0xfe, 0xa8, 0x8d, 0xf3, 0x58,
	0xf8, 0x14, 0x0b, 0x3f, 0x2b, 0x62, 0x0d, 0x6e, 0x1c, 0x2d, 0x3f, 0xfe, 0x74, 0xd0, 0x97, 0xc3,
	0xaa, 0x8f, 0x26, 0x8d, 0xbf, 0xa0, 0xe7, 0x47, 0xce, 0x58, 0x63, 0xac, 0xc0, 0x6c, 0x07, 0x04,
	0x18, 0xe3, 0xbe, 0x56, 0x95, 0x3d, 0x2a, 0x17, 0x7a, 0x34, 0xcf, 0x51, 0xe7, 0x2e, 0x2f, 0xcd,
	0x9b, 0x73, 0x60, 0x19, 0xf1, 0x04, 0x97, 0xca, 0xa3, 0x89, 0x22, 0xe9, 0x1c, 0x58, 0xeb, 0xea,
	0x85, 0xfc, 0xba, 0x86, 0x8c, 0xb9, 0x54, 0xa3, 0x02, 0xf1, 0x04, 0xff, 0xfe, 0xe4, 0xa0, 0xf7,
	0x87, 0x55, 0xff, 0x5e, 0xf9, 0x58, 0xde, 0xfd, 0x7b, 0x2e, 0xf9, 0xdb, 0x0c, 0x9e, 0xae, 0x77,
	0x36, 0xda, 0xec, 0x6c, 0xf4, 0x6b, 0x67, 0xa3, 0x0f, 0x7b, 0xdb, 0xd8, 0xec, 0x6d, 0xe3, 0xfb,
	0xde, 0x36, 0x5e, 0xdd, 0x3d, 0x01, 0x86, 0xff, 0x07, 0xa8, 0xa5, 0x20, 0x72, 0x5a, 0xd5, 0x21,
	0x1f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xab, 0xa7, 0xee, 0x46, 0x9c, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.StakeCap.Equal(that1.StakeCap) {
		return false
	}
	if this.WithdrawalGracePeriod != that1.WithdrawalGracePeriod {
		return false
	}
	if this.DeallocationGracePeriod != that1.DeallocationGracePeriod {
		return false
	}
	if this.ValuePostInterval != that1.ValuePostInterval {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ValuePostInterval, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ValuePostInterval):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.DeallocationGracePeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.DeallocationGracePeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.WithdrawalGracePeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.WithdrawalGracePeriod):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	{
		size := m.StakeCap.Size()
		i -= size
		if _, err := m.StakeCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StakeCap.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.WithdrawalGracePeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.DeallocationGracePeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ValuePostInterval)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakeCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.WithdrawalGracePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeallocationGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.DeallocationGracePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValuePostInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ValuePostInterval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
