// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bluechipchain/liquidityvault/valuepost.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValuePost is one snapshot of a vault's total value (active balance plus
// valued pool positions), taken at a pseudo-random time by the end blocker.
// The median of the last posts feeds the composite score, damping value
// swings and post-timing gaming, per the LPV design document.
type ValuePost struct {
	// value is the vault's total value in the bond denom at post time.
	Value cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=value,proto3,customtype=cosmossdk.io/math.Int" json:"value"`
	// post_time is when the snapshot was taken.
	PostTime time.Time `protobuf:"bytes,2,opt,name=post_time,json=postTime,proto3,stdtime" json:"post_time"`
}

func (m *ValuePost) Reset()         { *m = ValuePost{} }
func (m *ValuePost) String() string { return proto.CompactTextString(m) }
func (*ValuePost) ProtoMessage()    {}
func (*ValuePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8249c65eb90e81f7, []int{0}
}
func (m *ValuePost) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValuePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValuePost.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValuePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuePost.Merge(m, src)
}
func (m *ValuePost) XXX_Size() int {
	return m.Size()
}
func (m *ValuePost) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuePost.DiscardUnknown(m)
}

var xxx_messageInfo_ValuePost proto.InternalMessageInfo

func (m *ValuePost) GetPostTime() time.Time {
	if m != nil {
		return m.PostTime
	}
	return time.Time{}
}

// ValuePostHistory is a validator's rolling window of value posts, newest
// last, trimmed to the window size (6).
type ValuePostHistory struct {
	// validator_address is the operator address of the vault's owner.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// posts are the retained snapshots, oldest first.
	Posts []ValuePost `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts"`
}

func (m *ValuePostHistory) Reset()         { *m = ValuePostHistory{} }
func (m *ValuePostHistory) String() string { return proto.CompactTextString(m) }
func (*ValuePostHistory) ProtoMessage()    {}
func (*ValuePostHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_8249c65eb90e81f7, []int{1}
}
func (m *ValuePostHistory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValuePostHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValuePostHistory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValuePostHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuePostHistory.Merge(m, src)
}
func (m *ValuePostHistory) XXX_Size() int {
	return m.Size()
}
func (m *ValuePostHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuePostHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ValuePostHistory proto.InternalMessageInfo

func (m *ValuePostHistory) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValuePostHistory) GetPosts() []ValuePost {
	if m != nil {
		return m.Posts
	}
	return nil
}

// CachedPoolValue is the last successfully observed position value for a
// pool — the fallback used when the pool contract cannot be queried during
// a value post. Exported with genesis so an export/import round trip keeps
// the dark-pool fallback intact.
type CachedPoolValue struct {
	// pool_id is the pool the observation belongs to.
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// value is the last observed position value in the bond denom.
	Value cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=value,proto3,customtype=cosmossdk.io/math.Int" json:"value"`
}

func (m *CachedPoolValue) Reset()         { *m = CachedPoolValue{} }
func (m *CachedPoolValue) String() string { return proto.CompactTextString(m) }
func (*CachedPoolValue) ProtoMessage()    {}
func (*CachedPoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8249c65eb90e81f7, []int{2}
}
func (m *CachedPoolValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CachedPoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CachedPoolValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CachedPoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachedPoolValue.Merge(m, src)
}
func (m *CachedPoolValue) XXX_Size() int {
	return m.Size()
}
func (m *CachedPoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CachedPoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_CachedPoolValue proto.InternalMessageInfo

func (m *CachedPoolValue) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

// ScheduledValuePost is a pending entry in the value-post schedule.
type ScheduledValuePost struct {
	// validator_address is the operator address of the vault to snapshot.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// post_time is when the next snapshot is due.
	PostTime time.Time `protobuf:"bytes,2,opt,name=post_time,json=postTime,proto3,stdtime" json:"post_time"`
}

func (m *ScheduledValuePost) Reset()         { *m = ScheduledValuePost{} }
func (m *ScheduledValuePost) String() string { return proto.CompactTextString(m) }
func (*ScheduledValuePost) ProtoMessage()    {}
func (*ScheduledValuePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8249c65eb90e81f7, []int{3}
}
func (m *ScheduledValuePost) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduledValuePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduledValuePost.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduledValuePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledValuePost.Merge(m, src)
}
func (m *ScheduledValuePost) XXX_Size() int {
	return m.Size()
}
func (m *ScheduledValuePost) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledValuePost.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledValuePost proto.InternalMessageInfo

func (m *ScheduledValuePost) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ScheduledValuePost) GetPostTime() time.Time {
	if m != nil {
		return m.PostTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*ValuePost)(nil), "bluechipchain.liquidityvault.ValuePost")
	proto.RegisterType((*ValuePostHistory)(nil), "bluechipchain.liquidityvault.ValuePostHistory")
	proto.RegisterType((*CachedPoolValue)(nil), "bluechipchain.liquidityvault.CachedPoolValue")
	proto.RegisterType((*ScheduledValuePost)(nil), "bluechipchain.liquidityvault.ScheduledValuePost")
}

func init() {
	proto.RegisterFile("bluechipchain/liquidityvault/valuepost.proto", fileDescriptor_8249c65eb90e81f7)
}

var fileDescriptor_8249c65eb90e81f7 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0xeb, 0xb2, 0x8d, 0xd5, 0x3b, 0x30, 0x22, 0x10, 0xa5, 0x82, 0xb4, 0x54, 0x48, 0x54,
	0x82, 0x39, 0xd2, 0xb8, 0x23, 0x35, 0xbd, 0xd0, 0x0b, 0x9a, 0x32, 0xb4, 0x03, 0x97, 0xc8, 0x8d,
	0x4d, 0x62, 0xe1, 0xe4, 0x1f, 0x62, 0x27, 0xa2, 0x6f, 0x31, 0x9e, 0x82, 0x17, 0xd8, 0x43, 0xec,
	0x38, 0xed, 0x84, 0x38, 0x0c, 0xd4, 0xbe, 0x08, 0x72, 0x9c, 0x6c, 0x5a, 0x0f, 0x1c, 0x80, 0x5b,
	0xfe, 0xff, 0x7c, 0x9f, 0xbe, 0x9f, 0x3f, 0xcb, 0xf8, 0xd5, 0x42, 0x96, 0x3c, 0x4a, 0x44, 0x1e,
	0x25, 0x54, 0x64, 0x9e, 0x14, 0x9f, 0x4b, 0xc1, 0x84, 0x5e, 0x56, 0xb4, 0x94, 0xda, 0xab, 0xa8,
	0x2c, 0x79, 0x0e, 0x4a, 0x93, 0xbc, 0x00, 0x0d, 0xce, 0x93, 0x5b, 0x6a, 0x72, 0x5b, 0x3d, 0x78,
	0x1c, 0x81, 0x4a, 0x41, 0x85, 0xb5, 0xd6, 0xb3, 0x83, 0x35, 0x0e, 0x1e, 0xc4, 0x10, 0x83, 0xdd,
	0x9b, 0xaf, 0x66, 0x3b, 0x8c, 0x01, 0x62, 0xc9, 0xbd, 0x7a, 0x5a, 0x94, 0x1f, 0x3d, 0x2d, 0x52,
	0xae, 0x34, 0x4d, 0x73, 0x2b, 0x18, 0x7f, 0x45, 0xb8, 0x77, 0x62, 0x18, 0x8e, 0x40, 0x69, 0x67,
	0x8a, 0xb7, 0x6b, 0xa0, 0x3e, 0x1a, 0xa1, 0x49, 0xcf, 0x7f, 0x79, 0x7e, 0x35, 0xec, 0xfc, 0xb8,
	0x1a, 0x3e, 0xb4, 0x49, 0x8a, 0x7d, 0x22, 0x02, 0xbc, 0x94, 0xea, 0x84, 0xcc, 0x33, 0x7d, 0x79,
	0x76, 0x80, 0x1b, 0x84, 0x79, 0xa6, 0x03, 0xeb, 0x74, 0xa6, 0xb8, 0x67, 0x8e, 0x13, 0x9a, 0xa0,
	0x7e, 0x77, 0x84, 0x26, 0x7b, 0x87, 0x03, 0x62, 0x29, 0x48, 0x4b, 0x41, 0xde, 0xb7, 0x14, 0xfe,
	0xae, 0x89, 0x38, 0xfd, 0x39, 0x44, 0xc1, 0xae, 0xb1, 0x99, 0x1f, 0xe3, 0x6f, 0x08, 0xef, 0x5f,
	0x33, 0xbd, 0x15, 0x4a, 0x43, 0xb1, 0x74, 0xde, 0xe1, 0xfb, 0x15, 0x95, 0x82, 0x51, 0x0d, 0x45,
	0x48, 0x19, 0x2b, 0xb8, 0x52, 0x0d, 0xe6, 0xb3, 0xcb, 0xb3, 0x83, 0xa7, 0x0d, 0xc9, 0x49, 0xab,
	0x99, 0x5a, 0xc9, 0xb1, 0x2e, 0x44, 0x16, 0x07, 0xfb, 0xd5, 0xc6, 0xde, 0x99, 0xe1, 0x6d, 0x13,
	0xa8, 0xfa, 0xdd, 0xd1, 0x9d, 0xc9, 0xde, 0xe1, 0x0b, 0xf2, 0xa7, 0xe2, 0xc9, 0x35, 0x8e, 0xbf,
	0x65, 0x80, 0x03, 0xeb, 0x1d, 0xa7, 0xf8, 0xde, 0x8c, 0x46, 0x09, 0x67, 0x47, 0x00, 0xb2, 0xd6,
	0x38, 0x8f, 0xf0, 0xdd, 0x1c, 0x40, 0x86, 0x82, 0xd5, 0x74, 0x5b, 0xc1, 0x8e, 0x19, 0xe7, 0xec,
	0xa6, 0xdb, 0xee, 0xdf, 0x76, 0x6b, 0x8a, 0x71, 0x8e, 0x4d, 0x5c, 0x29, 0x39, 0xbb, 0xb9, 0xb5,
	0xff, 0x5d, 0xcd, 0xbf, 0x5f, 0xa1, 0xff, 0xe6, 0x7c, 0xe5, 0xa2, 0x8b, 0x95, 0x8b, 0x7e, 0xad,
	0x5c, 0x74, 0xba, 0x76, 0x3b, 0x17, 0x6b, 0xb7, 0xf3, 0x7d, 0xed, 0x76, 0x3e, 0x3c, 0x6f, 0x7b,
	0x9e, 0xd5, 0xcf, 0xe1, 0xcb, 0xe6, 0x83, 0xd0, 0xcb, 0x9c, 0xab, 0xc5, 0x4e, 0x9d, 0xf3, 0xfa,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x52, 0x4a, 0x2e, 0x3d, 0x03, 0x00, 0x00,
}

func (m *ValuePost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValuePost) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValuePost) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.PostTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PostTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintValuepost(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValuepost(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ValuePostHistory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValuePostHistory) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValuePostHistory) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Posts) > 0 {
		for iNdEx := len(m.Posts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Posts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintValuepost(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintValuepost(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CachedPoolValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CachedPoolValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CachedPoolValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValuepost(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.PoolId != 0 {
		i = encodeVarintValuepost(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduledValuePost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduledValuePost) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduledValuePost) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.PostTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PostTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintValuepost(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintValuepost(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintValuepost(dAtA []byte, offset int, v uint64) int {
	offset -= sovValuepost(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValuePost) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Value.Size()
	n += 1 + l + sovValuepost(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PostTime)
	n += 1 + l + sovValuepost(uint64(l))
	return n
}

func (m *ValuePostHistory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovValuepost(uint64(l))
	}
	if len(m.Posts) > 0 {
		for _, e := range m.Posts {
			l = e.Size()
			n += 1 + l + sovValuepost(uint64(l))
		}
	}
	return n
}

func (m *CachedPoolValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovValuepost(uint64(m.PoolId))
	}
	l = m.Value.Size()
	n += 1 + l + sovValuepost(uint64(l))
	return n
}

func (m *ScheduledValuePost) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovValuepost(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PostTime)
	n += 1 + l + sovValuepost(uint64(l))
	return n
}

func sovValuepost(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValuepost(x uint64) (n int) {
	return sovValuepost(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValuePost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValuepost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValuePost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValuePost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.PostTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValuepost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValuepost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValuePostHistory) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValuepost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValuePostHistory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValuePostHistory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Posts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Posts = append(m.Posts, ValuePost{})
			if err := m.Posts[len(m.Posts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValuepost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValuepost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CachedPoolValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValuepost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CachedPoolValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CachedPoolValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValuepost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValuepost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduledValuePost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValuepost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduledValuePost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduledValuePost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValuepost
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValuepost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.PostTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValuepost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValuepost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValuepost(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValuepost
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValuepost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValuepost
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValuepost
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValuepost
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValuepost        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValuepost          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValuepost = fmt.Errorf("proto: unexpected end of group")
)
