// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bluechipchain/liquidityvault/vault.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Vault is a validator's Liquidity Vault. It holds capital the validator has
// committed to providing liquidity to pools in the BlueChip network. The
// active balance counts toward the validator's composite score.
type Vault struct {
	// validator_address is the operator address of the validator that owns the
	// vault. Only this validator may deposit into or withdraw from it.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// balance is the active vault balance in the chain's bond denom. It counts
	// toward the validator's composite score.
	Balance cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=balance,proto3,customtype=cosmossdk.io/math.Int" json:"balance"`
	// delegator_reward_share is the fraction (in [0, 1]) of vault liquidity
	// rewards passed through to the validator's delegators; the remainder is
	// kept by the validator. This is the only vault parameter a validator can
	// change in stage 1 of the LPV rollout.
	DelegatorRewardShare cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=delegator_reward_share,json=delegatorRewardShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"delegator_reward_share"`
}

func (m *Vault) Reset()         { *m = Vault{} }
func (m *Vault) String() string { return proto.CompactTextString(m) }
func (*Vault) ProtoMessage()    {}
func (*Vault) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e4a8faccf87e224, []int{0}
}
func (m *Vault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vault.Merge(m, src)
}
func (m *Vault) XXX_Size() int {
	return m.Size()
}
func (m *Vault) XXX_DiscardUnknown() {
	xxx_messageInfo_Vault.DiscardUnknown(m)
}

var xxx_messageInfo_Vault proto.InternalMessageInfo

func (m *Vault) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

// PendingWithdrawal is a vault withdrawal waiting out the universal grace
// period. The amount has already been removed from the vault's active balance
// (it no longer counts toward the composite score) but remains held by the
// module until complete_time.
type PendingWithdrawal struct {
	// validator_address is the operator address of the withdrawing validator.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// amount is the withdrawal amount in the chain's bond denom.
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// complete_time is when the grace period ends and the funds are released to
	// the validator's account.
	CompleteTime time.Time `protobuf:"bytes,3,opt,name=complete_time,json=completeTime,proto3,stdtime" json:"complete_time"`
}

func (m *PendingWithdrawal) Reset()         { *m = PendingWithdrawal{} }
func (m *PendingWithdrawal) String() string { return proto.CompactTextString(m) }
func (*PendingWithdrawal) ProtoMessage()    {}
func (*PendingWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e4a8faccf87e224, []int{1}
}
func (m *PendingWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingWithdrawal.Merge(m, src)
}
func (m *PendingWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *PendingWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_PendingWithdrawal proto.InternalMessageInfo

func (m *PendingWithdrawal) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *PendingWithdrawal) GetCompleteTime() time.Time {
	if m != nil {
		return m.CompleteTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Vault)(nil), "bluechipchain.liquidityvault.Vault")
	proto.RegisterType((*PendingWithdrawal)(nil), "bluechipchain.liquidityvault.PendingWithdrawal")
}

func init() {
	proto.RegisterFile("bluechipchain/liquidityvault/vault.proto", fileDescriptor_6e4a8faccf87e224)
}

var fileDescriptor_6e4a8faccf87e224 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x93, 0x8a, 0x55, 0x47, 0x05, 0x1b, 0xaa, 0xac, 0xab, 0x26, 0x5a, 0x3c, 0x14, 0xa4,
	0x09, 0xea, 0x5d, 0x70, 0x5b, 0x0f, 0x0b, 0x22, 0x92, 0x4a, 0x05, 0x2f, 0x61, 0x32, 0xf3, 0x9c,
	0x0c, 0x4e, 0x66, 0xe2, 0xcc, 0x64, 0xeb, 0x7e, 0x02, 0xaf, 0xfd, 0x30, 0xfd, 0x10, 0x3d, 0x96,
	0x3d, 0x89, 0x87, 0x55, 0x76, 0x3f, 0x82, 0x5f, 0x40, 0x32, 0x49, 0xc4, 0x5d, 0x6f, 0xd2, 0x4b,
	0xc8, 0x7b, 0xf9, 0xbf, 0xdf, 0x3f, 0xbc, 0xff, 0x43, 0xbb, 0xb9, 0xa8, 0x81, 0x14, 0xbc, 0x22,
	0x05, 0xe6, 0x32, 0x11, 0xfc, 0x73, 0xcd, 0x29, 0xb7, 0xd3, 0x09, 0xae, 0x85, 0x4d, 0xdc, 0x33,
	0xae, 0xb4, 0xb2, 0x2a, 0xb8, 0xbf, 0xa2, 0x8c, 0x57, 0x95, 0xc3, 0xbb, 0x44, 0x99, 0x52, 0x99,
	0xcc, 0x69, 0x93, 0xb6, 0x68, 0x07, 0x87, 0xdb, 0x4c, 0x31, 0xd5, 0xf6, 0x9b, 0xb7, 0xae, 0x1b,
	0x31, 0xa5, 0x98, 0x80, 0xc4, 0x55, 0x79, 0xfd, 0x31, 0xb1, 0xbc, 0x04, 0x63, 0x71, 0x59, 0xb5,
	0x82, 0x9d, 0xaf, 0x1b, 0xe8, 0xf2, 0x51, 0xc3, 0x0e, 0xde, 0xa0, 0xad, 0x09, 0x16, 0x9c, 0x62,
	0xab, 0x74, 0x86, 0x29, 0xd5, 0x60, 0xcc, 0xc0, 0x7f, 0xe8, 0xef, 0x5e, 0x1b, 0x3d, 0x9a, 0x9d,
	0xee, 0x3d, 0xe8, 0xdc, 0x8e, 0x7a, 0xcd, 0xcb, 0x56, 0x72, 0x68, 0x35, 0x97, 0x2c, 0xbd, 0x35,
	0x59, 0xeb, 0x07, 0xaf, 0xd0, 0x95, 0x1c, 0x0b, 0x2c, 0x09, 0x0c, 0x36, 0x1c, 0xe5, 0xc9, 0xd9,
	0x3c, 0xf2, 0xbe, 0xcf, 0xa3, 0xdb, 0x2d, 0xc9, 0xd0, 0x4f, 0x31, 0x57, 0x49, 0x89, 0x6d, 0x11,
	0x8f, 0xa5, 0x9d, 0x9d, 0xee, 0xa1, 0xce, 0x62, 0x2c, 0x6d, 0xda, 0xcf, 0x06, 0x0c, 0xdd, 0xa1,
	0x20, 0x80, 0xb9, 0xdf, 0xd2, 0x70, 0x8c, 0x35, 0xcd, 0x4c, 0x81, 0x35, 0x0c, 0x2e, 0x39, 0xea,
	0xd3, 0x8e, 0x7a, 0xef, 0x5f, 0xea, 0x6b, 0x60, 0x98, 0x4c, 0x0f, 0x80, 0xfc, 0xc5, 0x3e, 0x00,
	0x92, 0x6e, 0xff, 0x01, 0xa6, 0x8e, 0x77, 0xd8, 0xe0, 0x76, 0x7e, 0xf9, 0x68, 0xeb, 0x2d, 0x48,
	0xca, 0x25, 0x7b, 0xcf, 0x6d, 0x41, 0x35, 0x3e, 0xc6, 0xe2, 0xc2, 0xb7, 0xb2, 0x8f, 0x36, 0x71,
	0xa9, 0x6a, 0x69, 0xff, 0x67, 0x29, 0xdd, 0x68, 0x30, 0x46, 0x37, 0x89, 0x2a, 0x2b, 0x01, 0x16,
	0xb2, 0x26, 0x50, 0xb7, 0x8a, 0xeb, 0xcf, 0x86, 0x71, 0x9b, 0x76, 0xdc, 0xa7, 0x1d, 0xbf, 0xeb,
	0xd3, 0x1e, 0x5d, 0x6d, 0x7c, 0x4e, 0x7e, 0x44, 0x7e, 0x7a, 0xa3, 0x1f, 0x6d, 0x3e, 0x8e, 0x5e,
	0x9c, 0x2d, 0x42, 0xff, 0x7c, 0x11, 0xfa, 0x3f, 0x17, 0xa1, 0x7f, 0xb2, 0x0c, 0xbd, 0xf3, 0x65,
	0xe8, 0x7d, 0x5b, 0x86, 0xde, 0x87, 0xc7, 0xfd, 0x25, 0xee, 0xbb, 0x9b, 0xfd, 0xb2, 0x7e, 0xb5,
	0x76, 0x5a, 0x81, 0xc9, 0x37, 0x9d, 0xd7, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x58,
	0x10, 0x27, 0xe2, 0x02, 0x00, 0x00,
}

func (m *Vault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.DelegatorRewardShare.Size()
		i -= size
		if _, err := m.DelegatorRewardShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Balance.Size()
		i -= size
		if _, err := m.Balance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintVault(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CompleteTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompleteTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintVault(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintVault(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVault(dAtA []byte, offset int, v uint64) int {
	offset -= sovVault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Vault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.Balance.Size()
	n += 1 + l + sovVault(uint64(l))
	l = m.DelegatorRewardShare.Size()
	n += 1 + l + sovVault(uint64(l))
	return n
}

func (m *PendingWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovVault(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompleteTime)
	n += 1 + l + sovVault(uint64(l))
	return n
}

func sovVault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVault(x uint64) (n int) {
	return sovVault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Vault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorRewardShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegatorRewardShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompleteTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CompleteTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVault = fmt.Errorf("proto: unexpected end of group")
)
